services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_APP_JWT_SECRET: ${JWT_SECRET}
      SPRING_APP_JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      SPRING_APP_JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    volumes:
      - .:/workspace
      - gradle-cache:/home/vscode/.gradle
      # Claude Code用の永続化設定（プロジェクト固有）
      - claude-config:/home/vscode/.claude
      - claude-history:/commandhistory
      - claude-npm-global:/home/vscode/.npm-global
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/book_chapter_page_contents.csv:/docker-entrypoint-initdb.d/book_chapter_page_contents.csv
      - ./db/book_favorites.csv:/docker-entrypoint-initdb.d/book_favorites.csv
      - ./db/book_genres.csv:/docker-entrypoint-initdb.d/book_genres.csv
      - ./db/book_reviews.csv:/docker-entrypoint-initdb.d/book_reviews.csv
      - ./db/books.csv:/docker-entrypoint-initdb.d/books.csv
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    command: --secure-file-priv=/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  gradle-cache:
  # Claude Code用のボリューム（プロジェクト固有）
  claude-config:      # Claude設定・認証情報
  claude-history:     # コマンド履歴
  claude-npm-global:  # npmグローバルパッケージ